# Generated by Django 4.0.2 on 2022-08-09 14:07

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('checked', models.BooleanField(default=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
