# Generated by Django 4.0.2 on 2022-08-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0004_alter_todolist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='checked',
            field=models.BooleanField(),
        ),
    ]
