# Generated by Django 4.0.2 on 2022-05-29 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('quantity_of_material', models.IntegerField(blank=True, default=0)),
                ('price', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('production_costs', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=128)),
                ('jp_candles', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_sale', models.DateField()),
                ('quantity_of_product', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='jp_app.product')),
                ('sales_channel', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sales', to='jp_app.sale')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_storage', models.DateField()),
                ('quantity_of_material', models.IntegerField()),
                ('price', models.IntegerField()),
                ('shop', models.CharField(blank=True, max_length=256)),
                ('url', models.URLField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='materials', to='jp_app.material')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='material_types', to='jp_app.materialtype')),
            ],
        ),
        migrations.CreateModel(
            name='Removal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_removal', models.DateField()),
                ('quantity_of_material', models.IntegerField()),
                ('note', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='removals', to='jp_app.material')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='removal_types', to='jp_app.materialtype')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='product_types', to='jp_app.producttype'),
        ),
        migrations.AddField(
            model_name='material',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='types', to='jp_app.materialtype'),
        ),
        # migrations.CreateModel(
        #     name='Idea',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=256)),
        #         ('production_costs', models.IntegerField()),
        #         ('selling_price', models.IntegerField()),
        #         ('introduction_day', models.DateField()),
        #         ('note', models.TextField(blank=True)),
        #         ('created', models.DateTimeField(auto_now_add=True)),
        #         ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='product_types_2', to='jp_app.producttype')),
        #     ],
        # ),
    ]
