# Generated by Django 4.0.2 on 2022-05-29 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jp_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('production_costs', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('introduction_day', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='product_types_2', to='jp_app.producttype')),
            ],
        ),
    ]
