# Generated by Django 4.0.2 on 2022-06-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jp_app', '0002_idea'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('in_process', 'in_process'), ('done', 'done')], default='waiting', max_length=256),
        ),
    ]
