# Generated by Django 4.0.2 on 2022-06-11 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jp_app', '0003_idea_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='idea',
            name='status',
            field=models.CharField(choices=[('Čeká na zahájení', 'Čeká na zahájení'), ('Připravuje se', 'Připravuje se'), ('Nastal problém', 'Nastal problém'), ('Hotovo', 'Hotovo')], default='Čeká na zahájení', max_length=256),
        ),
        migrations.AlterField(
            model_name='sale',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sale_types', to='jp_app.saletype'),
        ),
    ]
