# Generated by Django 4.0.2 on 2022-06-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jp_app', '0004_saletype_product_sold_alter_idea_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='jp_candles',
            field=models.BooleanField(default=True),
        ),
    ]
