# Generated by Django 4.0.2 on 2022-06-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jp_app', '0006_sale_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
        migrations.AddField(
            model_name='transaction',
            name='selling_price',
            field=models.IntegerField(default=0),
        ),
    ]
