# Generated by Django 4.0.2 on 2022-07-24 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jp_app', '0009_alter_idea_product_type_alter_material_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='day_of_sale',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity_of_product',
            field=models.IntegerField(default=1),
        ),
    ]
