# Generated by Django 4.0.2 on 2022-07-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jp_app', '0010_alter_transaction_day_of_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='total_price',
            field=models.IntegerField(blank=True),
        ),
    ]
