# Generated by Django 4.0.2 on 2022-07-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jp_app', '0011_alter_transaction_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('costs', models.IntegerField()),
                ('note', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='production_costs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='items',
            field=models.ManyToManyField(blank=True, default=None, related_name='prducts', to='jp_app.Item'),
        ),
    ]
