# Generated by Django 4.0.2 on 2022-07-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jp_app', '0012_item_product_note_alter_product_production_costs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='items',
            field=models.ManyToManyField(blank=True, default=[], related_name='products', to='jp_app.Item'),
        ),
    ]
