# Generated by Django 4.0.2 on 2022-07-29 17:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jp_app', '0015_alter_product_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='supplier',
            field=models.CharField(default=[], max_length=256),
        ),
        migrations.AddField(
            model_name='product',
            name='procedure',
            field=ckeditor.fields.RichTextField(
                blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='production_costs',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='idea',
            name='selling_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='costs',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='material',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='quantity_of_material',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storage',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='product_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity_of_product',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_price',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
