# Generated by Django 4.0.2 on 2022-07-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jp_app', '0020_alter_item_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='production_costs',
        ),
        migrations.AlterField(
            model_name='item',
            name='supplier',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
