# Generated by Django 4.0.2 on 2022-07-31 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jp_app', '0022_product_production_costs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['created']},
        ),
    ]
