# Generated by Django 4.0.2 on 2022-07-31 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jp_app', '0023_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-day_of_sale']},
        ),
    ]
