# Generated by Django 4.0.2 on 2022-08-14 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jp_app', '0025_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True, 'ordering': ['created']},
        ),
        migrations.AlterModelTable(
            name='product',
            table='products_db',
        ),
    ]
