# Generated by Django 4.0.2 on 2022-08-14 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jp_app', '0026_alter_product_options_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
